import type {AnalyticsReport} from "../analytics-report";
import {chatGPTSignOutPath} from "../chatgpt-auth";
import {siteOrigin} from "../seo";
const number=(n:number)=>n.toLocaleString("en-US");
const percent=(a:number,b:number)=>b?`${Math.round(a/b*100)}%`:"—";
const labels:Record<string,string>={page_view:"Page views",guest_started:"Guest sessions started",sign_in_started:"Sign-in started",dashboard_opened:"Dashboard opened",goal_created:"Goals created",income_recorded:"Income recorded",contribution_saved:"Goal funding saved",purchase_recorded:"Purchases recorded",history_edited:"History corrected",backup_restored:"Backups restored",import_completed:"Income imports",currency_changed:"Currency changed",gullie_opened:"Gullie opened",gullie_message_sent:"Messages sent to Gullie",gullie_reply_received:"Gullie replies",app_error:"Reported app errors",direct:"Direct / unknown",google:"Google",bing:"Bing",github:"GitHub",social:"Social referral",friends:"Friends campaign","bay-area-builders":"Bay Area Builders campaign",other:"Other referral","built-in":"Built-in replies",ai:"Connected AI replies"};
const label=(value:string|number)=>labels[String(value)]??String(value);
export default function ManageDashboard({report:r}:{report:AnalyticsReport}) {
  const feature=(name:string)=>r.features.find(x=>x.label===name)??{events:0,visitors:0};
  const max=Math.max(1,...r.daily.map(d=>Math.max(d.visitors,d.sessions)));
  const current=[{name:"Visitors",value:r.summary.visitors,previous:r.previous.visitors,note:"Distinct browsers"},{name:"Sessions",value:r.summary.sessions,previous:r.previous.sessions,note:"New after 30 minutes idle"},{name:"Page views",value:r.summary.pageViews,previous:r.previous.pageViews,note:"Includes return page loads"},{name:"Returning visitors",value:r.returning,note:"Seen on an earlier UTC day"},{name:"Seen in last 30 min",value:r.recent,note:"Latest recorded activity"},{name:"Synced accounts",value:r.accounts,note:"All registered accounts"}];
  return <main className="manage-shell">
    <header className="manage-top"><span className="manage-wordmark">gullak <small>manage</small></span><div><span className="manage-private">Owner only</span><a href={chatGPTSignOutPath("/manage")} target="_top">Sign out</a></div></header>
    <div className="manage-heading"><div><p className="manage-eyebrow">PRODUCT ANALYTICS</p><h1>How Gullak is being used</h1><p>Activity, adoption, and the people coming back.</p></div><form action="/manage" method="get"><label htmlFor="manage-days">Time range</label><select id="manage-days" name="days" defaultValue={String(r.days)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><button className="button primary" type="submit">Apply</button><a className="button secondary" href={`/manage?days=${r.days}`}>Refresh</a></form></div>
    <p className="manage-updated">Updated {new Date(r.until).toLocaleString("en-US",{timeZone:"UTC",dateStyle:"medium",timeStyle:"short"})} UTC · Current day is partial</p>
    {!r.summary.visitors&&<aside className="manage-empty"><strong>Ready for your first visitors.</strong><p>New usage will appear here as people open Gullak. Earlier traffic cannot be reconstructed. Your own visits to this management page are excluded.</p></aside>}
    <section className="manage-kpis" aria-label="Usage overview">{current.map(c=><article key={c.name}><p>{c.name}</p><strong>{number(c.value)}</strong><span>{c.note}</span>{c.previous!==undefined&&<small>{c.previous?`${c.value>=c.previous?"+":""}${Math.round((c.value-c.previous)/c.previous*100)}% vs previous ${r.days} days`:"No earlier baseline"}</small>}</article>)}</section>
    <section className="manage-panel manage-trend"><div className="manage-panel-heading"><div><h2>Daily activity</h2><p>Visitors and sessions, by UTC day.</p></div><div className="manage-legend"><span>Visitors</span><span>Sessions</span></div></div><div className="manage-chart" tabIndex={0} role="img" aria-label={`Daily visitors and sessions for ${r.days} days. Total ${r.summary.visitors} visitors and ${r.summary.sessions} sessions. Detailed values below.`}>{r.daily.map(d=><div className="manage-day" key={d.day} title={`${d.day}: ${d.visitors} visitors, ${d.sessions} sessions`}><div><i style={{height:`${d.visitors/max*100}%`}}/><i style={{height:`${d.sessions/max*100}%`}}/></div><span>{d.day.slice(5)}</span></div>)}</div><details className="manage-detail"><summary>View daily values</summary><div className="manage-table-scroll" tabIndex={0} role="region" aria-label="Scrollable daily activity table"><table><thead><tr><th>Date (UTC)</th><th>Visitors</th><th>Sessions</th><th>Page views</th></tr></thead><tbody>{r.daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{number(d.visitors)}</td><td>{number(d.sessions)}</td><td>{number(d.pageViews)}</td></tr>)}</tbody></table></div></details></section>
    <div className="manage-grid"><section className="manage-panel"><h2>Feature adoption</h2><p>Visitors who tried each feature in this period.</p><div className="manage-adoption">{["dashboard_opened","goal_created","income_recorded","contribution_saved","gullie_opened"].map(name=>{const f=feature(name);return <div key={name}><div><span>{label(name)}</span><strong>{number(f.visitors)} <small>{percent(f.visitors,r.summary.visitors)}</small></strong></div><meter min={0} max={Math.max(1,r.summary.visitors)} value={f.visitors}/></div>;})}</div><p className="manage-note">Adoption is measured separately for each feature; these are not sequential funnel steps.</p></section>
    <section className="manage-panel"><h2>Gullie usage</h2><p>Conversations and the replies people receive.</p><dl className="manage-stats"><div><dt>Visitors who opened Gullie</dt><dd>{number(feature("gullie_opened").visitors)}</dd></div><div><dt>Times opened</dt><dd>{number(feature("gullie_opened").events)}</dd></div><div><dt>Messages sent</dt><dd>{number(r.summary.messages)}</dd></div><div><dt>Replies received</dt><dd>{number(feature("gullie_reply_received").events)}</dd></div>{r.engines.map(e=><div key={e.label}><dt>{label(e.label)}</dt><dd>{number(e.events)}</dd></div>)}</dl><p className="manage-note">Only event counts and reply mode are recorded. Conversation text stays out of analytics.</p></section></div>
    <div className="manage-grid"><Breakdown title="Traffic sources" description="Session attribution from referrals and campaign links." rows={r.sources} metric="sessions"/><Breakdown title="Devices" description="Browsers used to access Gullak." rows={r.devices}/><Breakdown title="Home Screen and browser" description="Visits in standalone mode indicate an installed web app." rows={r.installation.map(x=>({...x,label:Number(x.label)===1?"Installed / standalone":"Browser tab"}))}/><Breakdown title="Guest and signed-in use" description="Access mode is verified by the server." rows={r.modes}/><Breakdown title="Operating systems" description="Broad device families, without raw device identifiers." rows={r.systems}/><Breakdown title="Browsers" description="Useful for prioritising compatibility checks." rows={r.browsers}/></div>
    <section className="manage-panel"><h2>Product activity</h2><p>Completed actions in this period, plus current totals for synced accounts.</p><div className="manage-product-totals"><div><strong>{number(r.summary.goalsCreated)}</strong><span>Goals created this period</span></div><div><strong>{number(r.savedGoals)}</strong><span>Current synced active goals</span></div><div><strong>{number(r.wins)}</strong><span>Current synced WINS</span></div><div><strong>{number(r.summary.errors)}</strong><span>Client-reported errors</span></div></div><div className="manage-table-scroll" tabIndex={0} role="region" aria-label="Scrollable product activity table"><table><thead><tr><th>Activity</th><th>Events</th><th>Visitors</th></tr></thead><tbody>{r.features.length?r.features.map(f=><tr key={f.label}><td>{label(f.label)}</td><td>{number(f.events)}</td><td>{number(f.visitors)}</td></tr>):<tr><td colSpan={3}>No activity recorded in this period.</td></tr>}</tbody></table></div><p className="manage-note">Action events include guests and signed-in users. Current account and goal totals include synced accounts only. No balances, earnings amounts, or goal names are shown.</p></section>
    <section className="manage-panel"><h2>Search visibility</h2><p>The public introduction is prepared for Google discovery. Personal dashboards and management are excluded from indexing.</p><div className="manage-seo"><div><span className="manage-check">Ready</span><h3>Search foundations</h3><p>Descriptive title, canonical address, crawlable product information, application structured data, and a sitemap.</p><a href="/sitemap.xml" target="_blank" rel="noreferrer">View public sitemap</a></div><div><span className={`manage-check ${r.searchConsoleVerified?"":"manage-pending"}`}>{r.searchConsoleVerified?"Property verified":"Verification pending"}</span><h3>Google search performance</h3><p>Impressions, search clicks, queries, and average position are available in Google Search Console after Google processes the site. Those reports are not imported into this dashboard. Visitor referrals from Google appear above when received.</p><a href={`https://search.google.com/search-console?resource_id=${encodeURIComponent(siteOrigin+"/")}`} target="_blank" rel="noreferrer">Open Gullak in Search Console</a><p className="manage-note">Use the URL-prefix property {siteOrigin}/ and submit sitemap.xml. Google controls indexing and ranking.</p></div></div></section>
    <footer className="manage-footer"><p>First-party usage analytics · Rolling 90-day reporting · Do Not Track and Global Privacy Control respected</p><p>Visitors are distinct browsers, not verified people. Sessions restart after 30 minutes idle. Privacy controls and browser storage can affect counts. Breakdowns can overlap when a visitor uses more than one mode. Historical traffic and Google ranking data are not invented.</p><a href="/privacy">Privacy details</a></footer>
  </main>;
}
function Breakdown({title,description,rows,metric="visitors"}:{title:string;description:string;rows:{label:string|number;visitors:number;sessions:number}[];metric?:"visitors"|"sessions"}) {
  const max=Math.max(1,...rows.map(x=>x[metric]));
  return <section className="manage-panel"><h2>{title}</h2><p>{description}</p><div className="manage-breakdown">{rows.length?rows.map(x=><div key={x.label}><div><span>{label(x.label)}</span><strong>{number(x[metric])} <small>{metric}</small></strong></div><span className="manage-track"><i style={{width:`${x[metric]/max*100}%`}}/></span></div>):<p className="manage-no-data">Waiting for activity in this period.</p>}</div></section>;
}
