import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare,createFetchMock}=wranglerRequire('miniflare');
const fetchMock=createFetchMock();fetchMock.disableNetConnect();
fetchMock.get("https://api.frankfurter.dev").intercept({path:"/v2/rates?base=USD",method:"GET"}).reply(200,JSON.stringify([{base:"USD",quote:"INR",rate:90,date:new Date().toISOString().slice(0,10)},{base:"USD",quote:"EUR",rate:.9,date:new Date().toISOString().slice(0,10)}]),{headers:{"Content-Type":"application/json"}}).persist();
fetchMock.get("https://www.amazon.com").intercept({path:"/dp/GULLAKTEST",method:"GET"}).reply(200,'<script type="application/ld+json">'+JSON.stringify({"@type":"Product",name:"Nintendo Game",description:"Game details",offers:{price:49.99,priceCurrency:"USD"}})+'</script>',{headers:{"Content-Type":"text/html"}}).persist();
const mf=new Miniflare({modules:[{type:'ESModule',path:resolve('dist/server/index.js')},...readdirSync('dist/server',{recursive:true}).filter(p=>p.endsWith('.js')&&p!=='index.js').map(p=>({type:'ESModule',path:resolve('dist/server',p)}))],modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'gullak-qa'},cf:false,fetchMock});
try{
 const db=await mf.getD1Database('DB');await db.exec(readFileSync('drizzle/0000_worried_microbe.sql','utf8').replace(/\n/g,' '));
 const base='https://gullak.test';const headers={'oai-authenticated-user-id':'qa-owner','oai-authenticated-user-email':'qa@test.invalid','Content-Type':'application/json'};
 const get=()=>mf.dispatchFetch(base+'/api/account',{headers});
 const post=(version,action,payload,requestId=crypto.randomUUID(),extra={})=>mf.dispatchFetch(base+'/api/account',{method:'POST',headers:{...headers,...extra},body:JSON.stringify({version,action,payload,requestId})});
 assert.equal((await mf.dispatchFetch(base+'/api/account')).status,401);
 assert.equal((await mf.dispatchFetch(base+'/api/rates')).status,401);
 const rateResponse=await mf.dispatchFetch(base+'/api/rates',{headers});assert.equal(rateResponse.status,200);assert.equal((await rateResponse.json()).rates.INR.rate,90);
 const anon=await mf.dispatchFetch(base+'/',{redirect:'manual'});assert.equal(anon.status,200);const welcome=await anon.text();assert.match(welcome,/Log In/);assert.match(welcome,/Create an Account/);assert.match(welcome,/Continue as a Guest/);assert.match(welcome,/signin-with-chatgpt/);assert.doesNotMatch(welcome,/qa@test.invalid/);assert.equal((await mf.dispatchFetch(base+'/api/gullie')).status,401);assert.equal((await mf.dispatchFetch(base+'/api/gullie',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:'Summarize my goals',history:[],today:new Date().toISOString().slice(0,10)})})).status,401);const guestRates=await mf.dispatchFetch(base+'/api/guest-rates');assert.equal(guestRates.status,200);assert.equal((await guestRates.json()).rates.INR.rate,90);assert.equal((await db.prepare('SELECT count(*) AS n FROM gullak_accounts').first()).n,0);
 const readProduct=(url,extra={})=>mf.dispatchFetch(base+'/api/product',{method:'POST',headers:{'Content-Type':'application/json',...extra},body:JSON.stringify({url})});
 const importedProduct=await readProduct('https://www.amazon.com/dp/GULLAKTEST');assert.equal(importedProduct.status,200);assert.match(importedProduct.headers.get('cache-control'),/no-store/);const details=await importedProduct.json();assert.equal(details.name,'Nintendo Game');assert.equal(details.price,49.99);assert.equal(details.currency,'USD');assert.equal((await db.prepare('SELECT count(*) AS n FROM gullak_accounts').first()).n,0);
 assert.equal((await readProduct('https://127.0.0.1/x')).status,400);assert.equal((await readProduct('https://www.amazon.com/dp/GULLAKTEST',{Origin:'https://other.invalid'})).status,403);
 const page=await mf.dispatchFetch(base+'/',{headers});assert.equal(page.status,200);const html=await page.text();assert.match(html,/GOALS/);assert.match(html,/noindex/);assert.doesNotMatch(html,/Starter Project/);
 let r=await get();assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);let s=await r.json();assert.equal(s.state.goals.length,5);assert.equal(s.state.entries.length,0);
 r=await post(s.version,'editGoal',{goalId:'monitor',name:'QA monitor',category:'Tech',targetCents:10000,date:'',note:''});assert.equal(r.status,200);s=await r.json();
 const id=crypto.randomUUID();r=await post(s.version,'income',{amountCents:20000,date:'2026-10-04',note:'QA deposit'},id);assert.equal(r.status,200);const income=await r.json();
 r=await post(s.version,'income',{amountCents:20000},id);assert.equal(r.status,200);assert.equal((await r.json()).state.entries.length,1);
 const concurrent=await Promise.all([post(income.version,'contribute',{goalId:'monitor',source:'pool',amountCents:7000}),post(income.version,'contribute',{goalId:'monitor',source:'pool',amountCents:8000})]);assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);
 s=await(await get()).json();assert.equal(s.state.entries.length,2);
 r=await post(s.version,'income',{amountCents:100},crypto.randomUUID(),{Origin:'https://other.invalid'});assert.equal(r.status,403);
 r=await post(s.version,'contribute',{goalId:'monitor',source:'pool',amountCents:999999});assert.equal(r.status,400);assert.equal((await(await get()).json()).version,s.version);
 r=await post(s.version,'purchase',{goalId:'monitor',amountCents:5000,confirmed:true});assert.equal(r.status,400);
 const amountSaved=s.state.entries.filter(e=>e.goalId==='monitor').reduce((n,e)=>n+e.goalDeltaCents,0);
 r=await post(s.version,'contribute',{goalId:'monitor',source:'pool',amountCents:10000-amountSaved});assert.equal(r.status,200);s=await r.json();
 r=await post(s.version,'purchase',{goalId:'monitor',amountCents:9000,confirmed:false});assert.equal(r.status,400);
 r=await post(s.version,'purchase',{goalId:'monitor',amountCents:9000,confirmed:true});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.goals[0].status,'purchased');
 r=await post(s.version,'createGoal',{name:'Car',category:'auto',targetCents:360000,date:'',note:''});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.goals.at(-1).category,'Getting around');
 const carId=s.state.goals.at(-1).id;
 r=await post(s.version,'contribute',{goalId:carId,source:'external',amountCents:2000});assert.equal(r.status,200);s=await r.json();
 r=await post(s.version,'closeGoal',{goalId:carId});assert.equal(r.status,400);
 r=await post(s.version,'closeGoal',{goalId:carId,reason:'bought',amountCents:5000,confirmed:true,date:'2026-10-04'});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.losses[0].amountCents,3000);assert.equal(s.state.goals.some(g=>g.id===carId),false);
 const persisted=await(await get()).json();assert.deepEqual(persisted.state.losses,s.state.losses);
 const ask=(text,extra={})=>mf.dispatchFetch(base+'/api/gullie',{method:'POST',headers:{...headers,...extra},body:JSON.stringify({text,history:[],today:new Date().toISOString().slice(0,10)})});
 const beforeAssistant=s.version;let answer=await ask('Summarize my goals');assert.equal(answer.status,200);let reply=await answer.json();assert.equal(reply.mode,'built-in');assert.equal(reply.version,s.version);assert.match(reply.reply,/recorded as earned income/);answer=await ask('I earned $20');assert.equal(answer.status,200);reply=await answer.json();assert.equal(reply.plan.action,'income');assert.equal(reply.plan.payload.amountCents,2000);assert.equal((await(await get()).json()).version,beforeAssistant);
 assert.equal((await ask('Summarize my goals',{Origin:'https://other.invalid'})).status,403);assert.equal((await mf.dispatchFetch(base+'/api/gullie',{method:'POST',headers,body:'bad JSON'})).status,400);
 const otherAnswer=await ask('Summarize my goals',{'oai-authenticated-user-id':'qa-other-gullie'});assert.equal(otherAnswer.status,200);assert.doesNotMatch((await otherAnswer.json()).reply,/QA monitor/);
 r=await post(s.version,'settings',{currency:'INR',gullieEnabled:false});assert.equal(r.status,200);s=await r.json();assert.equal((await(await get()).json()).state.settings.currency,'INR');assert.equal((await ask('Summarize my goals')).status,403);r=await post(s.version,'settings',{gullieEnabled:true});assert.equal(r.status,200);s=await r.json();assert.equal((await ask('Summarize my goals')).status,200);const refreshed=await mf.dispatchFetch(base+'/api/rates?refresh=1',{headers});assert.equal(refreshed.status,200);

 const lossPurchase=s.state.entries.find(e=>e.goalId===carId&&e.kind==='purchase');
 r=await post(s.version,'editEntry',{entryId:lossPurchase.id,amountCents:4000,date:'2026-10-04',note:'Corrected price'});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.losses[0].amountCents,2000);
 r=await post(s.version,'deleteEntry',{entryId:lossPurchase.id});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.losses.length,0);assert.equal(s.state.goals.find(g=>g.id===carId).targetCents,360000);
 r=await post(s.version,'resetGoal',{goalId:carId,confirmed:false});assert.equal(r.status,400);
 r=await post(s.version,'resetGoal',{goalId:carId,confirmed:true,date:'2026-10-05'});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.entries.filter(e=>e.goalId===carId).reduce((n,e)=>n+e.goalDeltaCents,0),0);
 const incomeEntry=s.state.entries.find(e=>e.kind==='income');r=await post(s.version,'editEntry',{entryId:incomeEntry.id,amountCents:18000,date:'2026-10-04',note:'Updated income'});assert.equal(r.status,200);s=await r.json();
 const oldLast=s.state.entries.at(-1).id;r=await post(s.version,'reset',{scope:'earned',confirmed:true});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.earningsFromEntry,oldLast);assert.ok(s.state.entries.length>0);
 r=await post(s.version,'income',{amountCents:1000});assert.equal(r.status,200);s=await r.json();const newIncome=s.state.entries.at(-1);
 r=await post(s.version,'deleteEntry',{entryId:newIncome.id});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.entries.some(e=>e.id===newIncome.id),false);
 r=await post(s.version,'reset',{scope:'history',confirmed:false});assert.equal(r.status,400);
 r=await post(s.version,'reset',{scope:'history',confirmed:true});assert.equal(r.status,200);s=await r.json();assert.equal(s.state.entries.length,0);assert.equal(s.state.goals[0].status,'active');
 const resetId=crypto.randomUUID();const oldVersion=s.version;r=await post(s.version,'reset',{scope:'all',confirmed:true},resetId);assert.equal(r.status,200);s=await r.json();assert.equal(s.state.goals.length,0);
 r=await post(oldVersion,'reset',{scope:'all',confirmed:true},resetId);assert.equal(r.status,200);assert.equal((await r.json()).version,s.version);assert.deepEqual((await(await get()).json()).state.entries,[]);
 const other=await mf.dispatchFetch(base+'/api/account',{headers:{...headers,'oai-authenticated-user-id':'qa-other'}});assert.equal(other.status,200);assert.equal((await other.json()).state.entries.length,0);
 console.log('Passed built Worker: public welcome with three flows, anonymous account/assistant denial, guest rate isolation, read-only assistant plans, Gullie disable guard, synced currency settings, SSR, sign-in gate, no-store, persistence, user isolation, idempotent retries, concurrent update conflicts, CSRF, currency feed, purchase gating, purchase losses, history edits/deletes, reset scopes, reset retries and overspend rejection.');
}finally{await mf.dispose();}
