"use client";
import { useId, useState } from "react";
import AmountSlider from "./amount-slider";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { convertInput, type Rates } from "./currency";
import { money } from "./domain";
export const currencyItems=(fx:Rates|null,current="USD")=>Array.from(new Set(["USD","INR",...Object.keys(fx?.rates??{}).sort(),current]));
export function CurrencySelect({value,onChange,fx,label}:{value:string;onChange:(v:string)=>void;fx:Rates|null;label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="currency-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{currencyItems(fx,value).map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select>;}
export function RateHelp({currency,fx,error,retry,manual}:{currency:string;fx:Rates|null;error:string;retry:()=>void;manual:(code:string,rate:number)=>void}){const [rate,setRate]=useState("");if(currency==="USD"||fx?.rates[currency])return null;return <div className="rate-help"><p role="status">{error||"Loading exchange rates…"}</p><button type="button" className="text-button" onClick={retry}>Retry Rates</button><details><summary>Enter a Rate Instead</summary><div className="manual-rate"><label>1 USD =<input aria-label={`${currency} per 1 USD`} inputMode="decimal" value={rate} onChange={e=>setRate(e.target.value)} placeholder="Exchange rate"/></label><span>{currency}</span><button type="button" className="button secondary" disabled={!Number.isFinite(Number(rate))||Number(rate)<=0} onClick={()=>manual(currency,Number(rate))}>Use Rate</button></div></details></div>;}
export default function CurrencyField({label,value,onChange,currency,onCurrency,fx,error,retry,manual,autoFocus=false,maxCents,defaultMaxCents,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;currency:string;onCurrency:(v:string)=>void;fx:Rates|null;error:string;retry:()=>void;manual:(code:string,rate:number)=>void;autoFocus?:boolean;maxCents?:number;defaultMaxCents?:number;disabled?:boolean}){
 const id=useId();
 let preview="";try{const c=convertInput(value,currency,fx);if(currency!=="USD")preview=`${money(c.cents)} USD · 1 USD = ${Number((fx?.rates[currency]?.rate??0).toFixed(4))} ${currency} · ${c.conversion?.rateDate}`;}catch{}
 return <div className="currency-field"><label className="form-label" htmlFor={id}>{label}</label><div className="currency-input-row"><input id={id} aria-label={label} disabled={disabled} value={value} onChange={e=>onChange(e.target.value)} inputMode="decimal" required data-autofocus={autoFocus||undefined} placeholder="0.00"/><CurrencySelect value={currency} onChange={onCurrency} fx={fx} label={`${label} currency`}/></div><AmountSlider label={label} value={value} onChange={onChange} currency={currency} fx={fx} maxCents={maxCents} defaultMaxCents={defaultMaxCents} disabled={disabled}/>{preview&&<p className="conversion-preview">{preview}</p>}<RateHelp currency={currency} fx={fx} error={error} retry={retry} manual={manual}/></div>;
}
