import type { Conversion } from "./currency";
export const categories = ["Tech", "Home", "Getting around", "Experiences", "Lifestyle"] as const;
export type Category = (typeof categories)[number];
export type Goal = { id:string; name:string; category:Category; targetCents:number; draft:boolean; date:string; note:string; status:"active"|"purchased"; earned:number; categoryOverride?:boolean; targetConversion?:Conversion; startedOn?:string };
export type GoalSymbol="car"|"bike"|"phone"|"laptop"|"monitor"|"tv"|"camera"|"headphones"|"home"|"plane"|"ticket"|"shirt"|"gift"|"book"|"dumbbell"|"watch"|"target";
const rules: { pattern: RegExp; category: Category; icon: GoalSymbol }[] = [
 {pattern:/\b(cars?|tesla|toyota|honda|civic|corolla|prius|bmw|mercedes|vehicle|automobile|ev|truck|suv)\b/i,category:"Getting around",icon:"car"},
 {pattern:/\b(scooter|bike|bicycle|motorcycle|ebike|e-bike)\b/i,category:"Getting around",icon:"bike"},
 {pattern:/\b(iphone\w*|phones?|smartphones?|pixel\w*|galaxy\w*)\b/i,category:"Tech",icon:"phone"},
 {pattern:/\b(macbook|laptop|computer|pc|ipad|tablet)\b/i,category:"Tech",icon:"laptop"},
 {pattern:/\b(monitors?|displays?)\b/i,category:"Tech",icon:"monitor"},
 {pattern:/\b(tv|television|projector)\b/i,category:"Home",icon:"tv"},
 {pattern:/\b(camera|gopro|lens)\b/i,category:"Tech",icon:"camera"},
 {pattern:/\b(headphones|earbuds|airpods|speaker)\b/i,category:"Tech",icon:"headphones"},
 {pattern:/\b(playstation|xbox|console|gaming|keyboard|mouse|gadget|tech)\b/i,category:"Tech",icon:"monitor"},
 {pattern:/\b(trip|travel|flight|vacation|holiday|hotel|airfare|getaway|journey)\b/i,category:"Experiences",icon:"plane"},
 {pattern:/\b(ticket|concert|festival|show|museum|experience|event|class|course)\b/i,category:"Experiences",icon:"ticket"},
 {pattern:/\b(sofa|furniture|desk|chair|bed|mattress|lamp|kitchen|fridge|refrigerator|oven|appliance|home|decor|coffee machine)\b/i,category:"Home",icon:"home"},
 {pattern:/\b(shirts?|clothes|clothing|shoes?|sneakers?|boots?|sandals?|jackets?|bags?|handbags?|dress|wardrobe)\b/i,category:"Lifestyle",icon:"shirt"},
 {pattern:/\b(watch|rolex|jewel|jewelry|jewellery)\b/i,category:"Lifestyle",icon:"watch"},
 {pattern:/\b(book|books|kindle)\b/i,category:"Lifestyle",icon:"book"},
 {pattern:/\b(gym|fitness|dumbbell|workout|exercise)\b/i,category:"Lifestyle",icon:"dumbbell"},
 {pattern:/\b(gift|present|birthday)\b/i,category:"Lifestyle",icon:"gift"},
];
export function classifyGoal(name:string) { const r=rules.find(r=>r.pattern.test(name));return r?{category:r.category,icon:r.icon}:null; }
export function categoryForGoal(g:Goal):Category { return g.categoryOverride?g.category:classifyGoal(g.name)?.category??g.category; }
export function symbolForGoal(g:Pick<Goal,"name">):GoalSymbol {return classifyGoal(g.name)?.icon??"target";}
export const categoryLabel=(c:Category)=>c==="Getting around"?"Mobility":c==="Experiences"?"Travel & experiences":c;

export type Entry = { id:string; kind:"income"|"save"|"allocate"|"release"|"purchase"|"withdraw"; amountCents:number; goalId:string|null; goalName:string; goalDeltaCents:number; poolDeltaCents:number; note:string; date:string; createdAt:string; sourceId?:string; conversion?:Conversion; shortfallCents?:number };
export type Loss={id:string;goalId:string;goalName:string;category:Category;costCents:number;fundedCents:number;amountCents:number;date:string};
export type State = { schemaVersion:1; goals:Goal[]; entries:Entry[]; appliedRequests:string[]; losses?:Loss[] };
export type Snapshot = { state:State; version:number; updatedAt:string };
export class DomainError extends Error { constructor(message:string) { super(message); this.name="DomainError"; } }
export const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:cents%100?2:0}).format(cents/100);
export const available=(s:State)=>s.entries.reduce((n,e)=>n+e.poolDeltaCents,0);
export const balance=(s:State,id:string)=>s.entries.filter(e=>e.goalId===id).reduce((n,e)=>n+e.goalDeltaCents,0);
export const reserved=(s:State)=>s.goals.reduce((n,g)=>n+balance(s,g.id),0);
export const losses=(s:State)=>(s.losses??[]).reduce((n,l)=>n+l.amountCents,0);
export const spent=(s:State)=>s.entries.filter(e=>e.kind==="purchase"||e.kind==="withdraw").reduce((n,e)=>n+e.amountCents,0);
export const received=(s:State)=>s.entries.filter(e=>e.kind==="income"||e.kind==="save").reduce((n,e)=>n+e.amountCents,0);
export const earnedIncome=(s:State)=>s.entries.filter(e=>e.kind==="income").reduce((n,e)=>n+e.amountCents,0);
export const goalTotals=(s:State)=>({targetCents:s.goals.filter(g=>g.status==="active").reduce((n,g)=>n+g.targetCents,0),fundedCents:reserved(s)});
function amount(v:unknown):number { if(!Number.isSafeInteger(v)||(v as number)<1||(v as number)>100000000)throw new DomainError("Enter an amount between $0.01 and $1,000,000.");return v as number; }
export function dollars(v:string):number { const x=v.trim().replace(/[$,]/g,"");if(!/^\d+(\.\d{1,2})?$/.test(x))throw new DomainError("Enter a dollar amount with up to two decimal places.");const [w,f=""]=x.split(".");return amount(Number(w)*100+Number(f.padEnd(2,"0"))); }
function txt(v:unknown,max:number,required=false):string {if(typeof v!=="string")throw new DomainError("Check your text fields.");const t=v.trim();if(t.length>max||(required&&!t))throw new DomainError(required?`Use a name with 1–${max} characters.`:`Keep this field under ${max} characters.`);return t;}
function date(v:unknown,optional=false):string {if(optional&&(v===""||v===undefined))return "";if(typeof v!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v+"T12:00:00Z"))||new Date(v+"T12:00:00Z").toISOString().slice(0,10)!==v||v<"2000-01-01"||v>"2100-12-31")throw new DomainError("Choose a valid date.");return v;}
function category(v:unknown):Category {if(!categories.includes(v as Category))throw new DomainError("Choose a category.");return v as Category;}
function conversion(v:unknown,cents:number):Conversion|undefined {if(v===undefined)return undefined;if(!v||typeof v!=="object")throw new DomainError("Check the currency conversion.");const x=v as Conversion;if(!/^[A-Z]{3}$/.test(x.currency)||x.currency==="USD"||!Number.isFinite(x.originalAmount)||x.originalAmount<=0||!Number.isFinite(x.usdRate)||x.usdRate<=0||Math.abs(Math.round(x.originalAmount*x.usdRate*100)-cents)>1)throw new DomainError("Check the converted amount.");return {currency:x.currency,originalAmount:x.originalAmount,usdRate:x.usdRate,rateDate:date(x.rateDate),source:txt(x.source,40,true)};}
function goalCategory(p:Record<string,unknown>,name:string){return p.category===undefined||p.category==="auto"?{category:classifyGoal(name)?.category??"Lifestyle" as Category,categoryOverride:false}:{category:category(p.category),categoryOverride:true};}
export function initialState():State {return {schemaVersion:1,entries:[],appliedRequests:[],goals:[
 {id:"monitor",name:"Desk monitor",category:"Tech",targetCents:40000},
 {id:"tv",name:"4K TV",category:"Home",targetCents:80000},
 {id:"scooter",name:"A little scooter",category:"Getting around",targetCents:70000},
 {id:"phone",name:"iPhone 18 Pro Max",category:"Tech",targetCents:160000},
 {id:"trip",name:"The next trip",category:"Experiences",targetCents:50000},
 ].map(g=>({...g,category:g.category as Category,draft:true,date:"",note:"",status:"active",earned:0}))};}
export function suggestSplit(s:State,total:number):{goalId:string;amountCents:number}[]{amount(total);const pending=s.goals.filter(g=>g.status==="active"&&!g.draft&&balance(s,g.id)<g.targetCents).map(g=>({id:g.id,left:g.targetCents-balance(s,g.id),value:0}));let rem=total;while(rem>0){const open=pending.filter(g=>g.left>0);if(!open.length)break;const share=Math.max(1,Math.floor(rem/open.length));for(const g of open){const take=Math.min(g.left,share,rem);g.value+=take;g.left-=take;rem-=take;if(!rem)break;}}return pending.filter(g=>g.value>0).map(g=>({goalId:g.id,amountCents:g.value}));}
export function assertAccounting(s:State){const pool=available(s),saved=reserved(s);if(!Number.isSafeInteger(pool)||pool<0||!Number.isSafeInteger(saved)||saved<0||s.goals.some(g=>balance(s,g.id)<0)||received(s)-spent(s)+losses(s)!==pool+saved||losses(s)!==s.entries.reduce((n,e)=>n+(e.shortfallCents??0),0))throw new DomainError("The balances do not match. Nothing was saved.");}
export function applyAction(original:State,action:string,raw:unknown,requestId:string,now=new Date().toISOString()):State{
 if(!/^[a-zA-Z0-9_-]{8,80}$/.test(requestId))throw new DomainError("Please retry this action.");
 if(original.appliedRequests.includes(requestId))return original;
 if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new DomainError("Check the details and try again.");
 const p=raw as Record<string,unknown>;let s:State=structuredClone(original);
 const find=(id:unknown)=>{const g=s.goals.find(g=>g.id===id);if(!g)throw new DomainError("This gullak no longer exists. Refresh and try again.");return g;};
 const add=(kind:Entry["kind"],amt:number,g:Goal|null,gd:number,pd:number,note?:string,entryDate?:string,entrySource?:string,entryConversion?:unknown,shortfallCents=0)=>{if(s.entries.length>=10000)throw new DomainError("Your ledger is full. Export a backup before adding more entries.");const source=entrySource??p.sourceId,fx=entryConversion??p.conversion;s.entries.push({id:requestId+"-"+s.entries.length,kind,amountCents:amt,goalId:g?.id??null,goalName:g?.name??"",goalDeltaCents:gd,poolDeltaCents:pd,note:note??txt(p.note??"",200),date:date(entryDate??p.date??now.slice(0,10)),createdAt:now,...(typeof source==="string"?{sourceId:txt(source,200)}:{}),...(fx&&kind!=="release"?{conversion:conversion(fx,amt)}:{}),...(shortfallCents?{shortfallCents}:{})});};
 switch(action){
 case "createGoal":{if(s.goals.length>=100)throw new DomainError("You can keep up to 100 gullaks.");const name=txt(p.name,60,true),targetCents=amount(p.targetCents);s.goals.push({id:requestId,name,...goalCategory(p,name),targetCents,date:date(p.date,true),note:txt(p.note??"",300),status:"active",draft:false,earned:0,targetConversion:conversion(p.targetConversion,targetCents),startedOn:date(p.startedOn??now.slice(0,10))});break;}
 case "editGoal":{const g=find(p.goalId);if(g.status!=="active")throw new DomainError("Purchased goals stay in your collection.");const name=txt(p.name,60,true),targetCents=amount(p.targetCents);Object.assign(g,{name,...goalCategory(p,name),targetCents,date:date(p.date,true),note:txt(p.note??"",300),draft:false,targetConversion:conversion(p.targetConversion,targetCents),startedOn:g.startedOn??(g.draft?date(p.startedOn??now.slice(0,10)):undefined)});break;}
 case "deleteGoal":{const g=find(p.goalId);if(g.status!=="active")throw new DomainError("Purchased goals stay in WINS.");if(balance(s,g.id))throw new DomainError("Release this gullak’s money before deleting it.");if(!["changed","otherGoal"].includes(p.reason as string))throw new DomainError("Choose why you are deleting this goal.");s.goals=s.goals.filter(x=>x.id!==g.id);break;}
 case "closeGoal":{const g=find(p.goalId);if(g.status!=="active")throw new DomainError("This goal is already closed.");if(!["bought","changed","otherGoal"].includes(p.reason as string))throw new DomainError("Choose why you are closing this goal.");const saved=balance(s,g.id);
  if(p.reason==="bought"){const cost=amount(p.amountCents);if(p.confirmed!==true)throw new DomainError("Confirm that you already made this purchase.");const funded=Math.min(saved,cost),gap=cost-funded;add("purchase",cost,g,-funded,0,undefined,undefined,undefined,p.conversion,gap);const purchase=s.entries.at(-1)!;if(saved>cost)add("release",saved-cost,g,-(saved-cost),saved-cost,"Left over after purchase");if(gap){s.losses=[...(s.losses??[]),{id:purchase.id,goalId:g.id,goalName:g.name,category:categoryForGoal(g),costCents:cost,fundedCents:funded,amountCents:gap,date:purchase.date}];}if(!gap&&!g.draft&&saved>=g.targetCents){g.status="purchased";g.earned=4;}else s.goals=s.goals.filter(x=>x.id!==g.id);
  }else{if(saved)add("release",saved,g,-saved,saved,p.reason==="changed"?"No longer wanted":"Saving for another goal");s.goals=s.goals.filter(x=>x.id!==g.id);}break;}
 case "income":{const amt=amount(p.amountCents);if(p.sourceId&&s.entries.some(e=>e.sourceId===p.sourceId))throw new DomainError("This statement entry is already recorded.");add("income",amt,null,0,amt);break;}
 case "importIncome":{if(!Array.isArray(p.entries)||!p.entries.length||p.entries.length>5000)throw new DomainError("Choose between 1 and 5,000 deposits.");const seen=new Set(s.entries.map(e=>e.sourceId).filter(Boolean));let count=0;for(const raw of p.entries){if(!raw||typeof raw!=="object")throw new DomainError("Check the statement entries.");const e=raw as Record<string,unknown>,id=txt(e.sourceId,200,true);if(!/^csv-[a-f0-9]{64}$/.test(id))throw new DomainError("This statement entry could not be verified.");if(seen.has(id))continue;const amt=amount(e.amountCents);add("income",amt,null,0,amt,txt(e.note,200),date(e.date),id,e.conversion);seen.add(id);count++;}if(!count)throw new DomainError("These deposits are already recorded.");break;}
 case "contribute":{const g=find(p.goalId),amt=amount(p.amountCents);if(g.status!=="active")throw new DomainError("This goal has already been purchased.");if(g.draft)throw new DomainError("Confirm this gullak’s target budget before adding money.");if(p.source!=="pool"&&p.source!=="external")throw new DomainError("Choose where this money comes from.");if(p.source==="pool"&&amt>available(s))throw new DomainError("There isn’t enough unallocated money. Choose existing savings instead.");add(p.source==="pool"?"allocate":"save",amt,g,amt,p.source==="pool"?-amt:0);break;}
 case "split":{if(!Array.isArray(p.allocations)||!p.allocations.length||p.allocations.length>100)throw new DomainError("Choose at least one gullak.");const a=p.allocations as {goalId:string;amountCents:number}[];if(new Set(a.map(x=>x.goalId)).size!==a.length)throw new DomainError("Each gullak can appear once in a split.");const total=a.reduce((n,x)=>n+amount(x.amountCents),0);if(!Number.isSafeInteger(total)||total>available(s))throw new DomainError("This split is larger than your unallocated money.");for(const x of a){const g=find(x.goalId);if(g.status!=="active"||g.draft)throw new DomainError("Confirm the target budgets for this split.");add("allocate",x.amountCents,g,x.amountCents,-x.amountCents);}break;}
 case "release":{const g=find(p.goalId),amt=amount(p.amountCents);if(amt>balance(s,g.id))throw new DomainError("You can only release money already reserved here.");add("release",amt,g,-amt,amt);break;}
 case "purchase":{const g=find(p.goalId),amt=amount(p.amountCents),saved=balance(s,g.id);if(g.status!=="active"||g.draft)throw new DomainError("Confirm this goal before recording a purchase.");if(saved<g.targetCents)throw new DomainError("Reach the Set Goal amount before confirming a purchase.");if(p.confirmed!==true)throw new DomainError("Confirm that you have made this purchase.");if(amt>saved)throw new DomainError("The purchase cost is greater than the money in this gullak.");add("purchase",amt,g,-amt,0);if(saved>amt)add("release",saved-amt,g,-(saved-amt),saved-amt,"Left over after purchase");g.status="purchased";g.earned=4;break;}
 case "withdraw":{const amt=amount(p.amountCents);if(amt>available(s))throw new DomainError("You can only remove money that is unallocated.");add("withdraw",amt,null,0,-amt);break;}
 case "restore":s=validateBackup(p.state);break;
 default:throw new DomainError("That action is not supported.");
 }
 for(const g of s.goals)if(!g.draft)g.earned=Math.max(g.earned,Math.min(4,Math.floor(balance(s,g.id)*4/g.targetCents)));
 s.appliedRequests=[...s.appliedRequests,requestId].slice(-200);assertAccounting(s);return s;
}
export function validateBackup(input:unknown):State{
 if(!input||typeof input!=="object")throw new DomainError("This is not a Gullak backup.");const s=input as State;
 if(s.schemaVersion!==1||!Array.isArray(s.goals)||!Array.isArray(s.entries)||s.goals.length>100||s.entries.length>10000)throw new DomainError("This backup format is not supported.");
 const ids=new Set<string>();const goals:Goal[]=s.goals.map(g=>{const id=txt(g.id,80,true);if(ids.has(id))throw new DomainError("This backup has duplicate gullaks.");ids.add(id);if(typeof g.draft!=="boolean"||!["active","purchased"].includes(g.status)||!Number.isInteger(g.earned)||g.earned<0||g.earned>4)throw new DomainError("This backup has an invalid gullak.");return {id,name:txt(g.name,60,true),category:category(g.category),targetCents:amount(g.targetCents),date:date(g.date,true),note:txt(g.note,300),status:g.status,draft:g.draft,earned:g.earned,...(typeof g.categoryOverride==="boolean"?{categoryOverride:g.categoryOverride}:{}),...(g.targetConversion?{targetConversion:conversion(g.targetConversion,g.targetCents)}:{}),...(g.startedOn?{startedOn:date(g.startedOn)}:{})};});
 const entryIds=new Set<string>(),sourceIds=new Set<string>();const entries:Entry[]=s.entries.map(e=>{const id=txt(e.id,160,true);if(entryIds.has(id))throw new DomainError("This backup has duplicate entries.");entryIds.add(id);const amt=amount(e.amountCents),gd=e.goalDeltaCents,pd=e.poolDeltaCents;
 if(!Number.isSafeInteger(gd)||!Number.isSafeInteger(pd)||!["income","save","allocate","release","purchase","withdraw"].includes(e.kind))throw new DomainError("This backup has an invalid entry.");const gap=e.shortfallCents??0;if(!Number.isSafeInteger(gap)||gap<0||gap>amt||(gap&&e.kind!=="purchase"))throw new DomainError("Invalid purchase shortfall.");const expected:Record<Entry["kind"],[number,number]>={income:[0,amt],save:[amt,0],allocate:[amt,-amt],release:[-amt,amt],purchase:[-(amt-gap),0],withdraw:[0,-amt]};
 if(gd!==expected[e.kind][0]||pd!==expected[e.kind][1]||(["income","withdraw"].includes(e.kind)?e.goalId!==null:typeof e.goalId!=="string"))throw new DomainError("This backup has an inconsistent entry.");
 if(typeof e.createdAt!=="string"||Number.isNaN(Date.parse(e.createdAt)))throw new DomainError("This backup has an invalid timestamp.");let sourceId:string|undefined;if(e.sourceId){sourceId=txt(e.sourceId,200);if(sourceIds.has(sourceId))throw new DomainError("This backup has duplicate statement entries.");sourceIds.add(sourceId);}
 return {id,kind:e.kind,amountCents:amt,goalId:e.goalId===null?null:txt(e.goalId,80,true),goalName:txt(e.goalName,60),goalDeltaCents:gd,poolDeltaCents:pd,date:date(e.date),note:txt(e.note,200),createdAt:e.createdAt,...(sourceId?{sourceId}:{}),...(e.conversion?{conversion:conversion(e.conversion,amt)}:{}),...(gap?{shortfallCents:gap}:{})};});
 if(s.losses!==undefined&&(!Array.isArray(s.losses)||s.losses.length>10000))throw new DomainError("Invalid losses in backup.");
 const lossIds=new Set<string>();const savedLosses=(s.losses??[]).map(l=>{const id=txt(l.id,160,true),entry=entries.find(e=>e.id===id);if(lossIds.has(id)||!entry||entry.kind!=="purchase"||entry.shortfallCents!==l.amountCents||entry.amountCents!==l.costCents||entry.goalId!==l.goalId||entry.goalName!==l.goalName||entry.date!==l.date||l.fundedCents!==l.costCents-l.amountCents)throw new DomainError("This backup has an inconsistent loss.");lossIds.add(id);return {id,goalId:txt(l.goalId,80,true),goalName:txt(l.goalName,60,true),category:category(l.category),costCents:amount(l.costCents),fundedCents:l.fundedCents,amountCents:amount(l.amountCents),date:date(l.date)};});
 const result:State={schemaVersion:1,goals,entries,appliedRequests:[],losses:savedLosses};for(const id of new Set(entries.filter(e=>e.goalId).map(e=>e.goalId!)))if(!ids.has(id)&&balance(result,id)!==0)throw new DomainError("This backup has money in a missing gullak.");if(goals.some(g=>g.status==="purchased"&&balance(result,g.id)!==0))throw new DomainError("Purchased gullaks must have no reserved balance.");assertAccounting(result);return result;
}
