import { applyAction, available, balance, earnedIncome, goalTotals, losses, reserved, settingsFor, suggestSplit, categoryLabel, type State, type Goal } from "./domain";
import { convertInput, formatCurrency, type Rates } from "./currency";
import { goalEta } from "./eta";

export type GulliePlan = {kind:"mutation";action:string;payload:Record<string,unknown>;description:string}|{kind:"open";screen:"goal"|"income"|"close"|"entry"|"reset"|"settings"|"history";goalId?:string;entryId?:string;description:string};
export type GullieAnswer={reply:string;plan?:GulliePlan;readAloud?:boolean;handled:boolean;mode?:"built-in"|"ai";version?:number};
export type ChatTurn={role:"user"|"assistant";text:string};
const words:Record<string,number>={zero:0,one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90};
// Only normalize spoken numbers next to a currency or a monetary command cue.
export function spokenAmount(input:string){return input.replace(/\b((?:(?:zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|million|lakh|crore|and)[ -]+)+)(dollars?|rupees?|usd|inr)\b/gi,(_,phrase:string,currency:string)=>{let total=0,group=0;for(const w of phrase.toLowerCase().trim().split(/[ -]+/)){if(w==="and")continue;if(words[w]!==undefined)group+=words[w];else if(w==="hundred")group=Math.max(group,1)*100;else{const scale={thousand:1000,million:1000000,lakh:100000,crore:10000000}[w as "thousand"];if(scale){total+=Math.max(group,1)*scale;group=0;}}}return `${total+group} ${currency}`;});}
function findAmount(text:string,currency:string,fx:Rates|null){const normalized=spokenAmount(text);if(/-\s*(?:[$₹€£]|USD|INR|EUR|GBP)?\s*\d|(?:[$₹€£]|USD|INR|EUR|GBP)\s*-\s*\d|\d[\d,]*\.\d{3,}/i.test(normalized))throw new Error("Use a positive amount with no more than two decimal places.");if([...normalized.matchAll(/(?:[$₹€£]|\bUSD|\bINR|\bEUR|\bGBP)\s*\d[\d,]*(?:\.\d{1,2})?|\b\d[\d,]*(?:\.\d{1,2})?\s*(?:dollars?|rupees?|USD|INR|EUR|GBP)\b/gi)].length>1)throw new Error("Give one amount per request so I don’t choose the wrong number.");const patterns=[/([$₹€£])\s*(\d[\d,]*(?:\.\d{1,2})?)/i,/\b(USD|INR|EUR|GBP)\s*(\d[\d,]*(?:\.\d{1,2})?)/i,/\b(\d[\d,]*(?:\.\d{1,2})?)\s*(dollars?|rupees?|USD|INR|EUR|GBP)\b/i];for(let i=0;i<patterns.length;i++){const match=patterns[i].exec(normalized);if(!match)continue;const unit=i===2?match[2]:match[1],amount=i===2?match[1]:match[2];const code=/^(\$|dollars?|USD)$/i.test(unit)?"USD":/^(₹|rupees?|INR)$/i.test(unit)?"INR":/^(€|EUR)$/i.test(unit)?"EUR":"GBP";return {...convertInput(amount,code,fx),currency:code,input:amount,match:match[0],normalized};}const cue=/\b(?:budget(?:\s+of)?|target(?:\s+of)?|for|earned|income(?:\s+of)?|add|deposit|reserve|allocate|release|withdraw|split)\s+(\d[\d,]*(?:\.\d{1,2})?)(?![\d.])/i.exec(normalized);return cue?{...convertInput(cue[1],currency,fx),currency,input:cue[1],match:cue[1],normalized}:null;}
function matchedGoals(s:State,text:string){const clean=(x:string)=>x.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();const query=clean(text);const all=s.goals.filter(g=>g.status==="active");const exact=all.filter(g=>query.includes(clean(g.name)));if(exact.length)return exact;return all.filter(g=>{const tokens=clean(g.name).split(" ").filter(w=>w.length>2&&!['desk','new','small','goal','the'].includes(w));return tokens.length>0&&tokens.every(w=>query.split(" ").includes(w));});}
const safeMutation=(s:State,action:string,payload:Record<string,unknown>,description:string):GullieAnswer=>{try{applyAction(s,action,payload,"gullie-preview-action");return {reply:description+" Review it below before saving.",handled:true,plan:{kind:"mutation",action,payload,description}};}catch(e){return {reply:(e as Error).message+" Nothing has changed.",handled:true};}};
export function dashboardSummary(s:State,fx:Rates|null,today:string,expanded=false){const currency=settingsFor(s).currency,fmt=(n:number)=>formatCurrency(n,currency,fx),active=s.goals.filter(g=>g.status==="active"),wins=s.goals.filter(g=>g.status==="purchased"),totals=goalTotals(s);let text=`${currency!=="USD"&&!fx?.rates[currency]?"INR rates are unavailable; amounts below are shown in USD.\n":""}You have ${active.length} active ${active.length===1?"goal":"goals"}, totaling ${fmt(totals.targetCents)}. ${fmt(reserved(s))} is funded, ${fmt(available(s))} is available to allocate, and ${fmt(earnedIncome(s))} is recorded as earned income.\n${wins.length} ${wins.length===1?"win":"wins"}${losses(s)?`, with ${fmt(-losses(s))} in purchase shortfalls`:""}.`;if(expanded){for(const g of active){const funded=balance(s,g.id),eta=goalEta(s,g,today);text+=`\n• ${g.name}: ${fmt(funded)} of ${fmt(g.targetCents)} (${Math.min(100,Math.round(funded/g.targetCents*100))}%). ${g.draft?"Confirm its budget first.":funded>=g.targetCents?"Ready to buy; confirm only after purchase.":`${fmt(g.targetCents-funded)} left.${eta?` ETA ${eta.date??"long-term"}, if your pace continues.`:" ETA appears after a first deposit."}`}`;}text+="\nEarned counts income entries. Funded counts money reserved for goals; savings added directly to goals do not increase Earned. Available is money you have recorded but have not allocated. Goals are reservations in this tracker; it does not move bank money.";}return text;}

export function respondToGullie(s:State,input:string,fx:Rates|null,today:string,history:ChatTurn[]=[]):GullieAnswer{
 let raw=input.trim();const previous=history.findLast(t=>t.role==="user")?.text;if(previous&&/^(?:from (?:income|available|pool|savings|new money|external)|[$₹€£]\s*\d[\d,.]*|\d[\d,.]*\s*(?:USD|INR|dollars?|rupees?))\s*[.!]?$/i.test(raw))raw=previous+" "+raw;const text=raw.toLowerCase(),currency=settingsFor(s).currency,fmt=(n:number)=>formatCurrency(n,currency,fx);const readAloud=/\b(?:read|say|speak)\b.*\b(?:aloud|loud|to me|back)\b|\bspeak\b/i.test(raw);
 const reply=(content:string,handled=true):GullieAnswer=>({reply:content,handled,readAloud});
 if(raw.length>1500)return reply("Keep your message under 1,500 characters.");
 if(/\b(api.?key|password|credit.?card number|bank login|social security|ssn|execute code|system prompt|ignore (?:previous|all)|bypass|hack|transfer (?:money|cash)|send (?:money|email)|buy stocks|crypto|investment advice|tax advice)\b/.test(text))return reply("I can help with your Gullak goals, earnings, allocations, history, and settings. I can’t handle credentials, move real money, execute code, or provide investment or tax advice.");
 if(/what.*(?:remember|preference)/.test(text))return reply(settingsFor(s).gullieNotes.length?settingsFor(s).gullieNotes.map(n=>`• ${n}`).join("\n"):"I have no saved preferences. Say ‘Remember that travel is my savings priority’ to add one after review.");
 if(/\b(remember|learn)\b/.test(text)){const note=raw.replace(/^.*?\b(?:remember|learn)\s*(?:that\s*)?/i,"").trim();if(!/\b(goal|saving|save|gullak|budget|tech|travel|trip|car|income|earn|allocate|allocation|priority|prioritize|currency|usd|inr|rupees|dollars|summary|summaries|brief|concise|detailed)\b/i.test(note))return reply("I can remember preferences about goals, saving, allocations, currency, and how you like dashboard explanations. What product preference should I remember?");return safeMutation(s,"remember",{note},`Remember: “${note}”`);}
 if(/\bforget\b/.test(text))return safeMutation(s,"forget",{all:true},"Forget all saved Gullie preferences. Your goals and money stay.");

 if(readAloud){const named=matchedGoals(s,raw);if(named.length===1){const g=named[0];return reply(`${g.name}. Current ${fmt(balance(s,g.id))}. Goal ${fmt(g.targetCents)}. ${fmt(Math.max(0,g.targetCents-balance(s,g.id)))} remaining.`);}if(/summary|goals|balance|earn|fund/.test(text))return reply(dashboardSummary(s,fx,today,/goals/.test(text)));const previous=history.findLast(t=>t.role==="assistant");return reply(previous?.text??dashboardSummary(s,fx,today));}
 if(/\b(expand|more detail|explain (?:more|that|this|it)|break (?:it|that) down|detailed|walk me through)\b/.test(text))return reply(dashboardSummary(s,fx,today,true));
 if(/\b(summary|summarize|summarise)\b/.test(text)&&/conversation|chat|discuss/.test(text))return reply(history.length?"We discussed:\n"+history.filter(t=>t.role==="user").slice(-5).map(t=>`• ${t.text.slice(0,150)}`).join("\n")+"\nA proposal is only saved after you review and confirm it.":"We haven’t discussed any dashboard topics yet.");
 if(/\b(summary|summarize|summarise|overview|how am i doing|my progress|all my goals)\b/.test(text))return reply(dashboardSummary(s,fx,today,/goals/.test(text)));
 if(/^(hi|hello|hey|thanks|thank you)[!.\s]*$/.test(text))return reply(/thanks|thank you/.test(text)?"You’re welcome. Keep making room for what matters to you.":"Hi, I’m Gullie. I can summarize your goals, explain balances, plan allocations, and prepare changes. Try ‘Create a monitor goal for $400’ or ‘I earned fifty dollars’. Changes always need your review.");
 if(/\b(what can you|help|abilities|can you do)\b/.test(text))return reply("I can create and edit goals, record earnings, allocate or release money, guide purchases and deletions, edit history, suggest a split, explain ETA, summarize or expand your dashboard, remember product preferences, switch currency, and read answers aloud when asked. I prepare changes for your review. I can’t access bank accounts or make purchases.");
 const matches=matchedGoals(s,raw),g=matches.length===1?matches[0]:null;
 const needGoal=()=>reply(matches.length>1?`Which goal? ${matches.map(g=>g.name).join(", ")}. Use its full name.`:"Which goal do you mean? Include its name.");
 const open=(screen:Extract<GulliePlan,{kind:"open"}>["screen"],description:string,goalId?:string,entryId?:string):GullieAnswer=>({reply:description,handled:true,plan:{kind:"open",screen,description,goalId,entryId}});
 if(/\b(history|transaction|entry)\b/.test(text)&&/\b(edit|change|delete|remove)\b/.test(text)){if(/latest|last/.test(text)){const e=s.entries.findLast(e=>!/earning|income/.test(text)||e.kind==="income");if(!e)return reply("There are no matching history entries yet.");return open("entry","Review this entry in History. Edit or delete it there so dependent balances are recalculated.",undefined,e.id);}return open("history","Choose the history entry you want to edit or delete. I won’t guess between transactions.");}
 if(/\breset\b/.test(text))return open("reset","Choose exactly what to reset, then review its effect before confirming.");
 if(/\b(settings|theme|dark mode|light mode|disable gullie|enable gullie)\b/.test(text))return open("settings","You can change appearance, currency, and Gullie in Settings.");
 if(/\b(?:switch|change|use|display)\b.*\b(?:usd|inr|rupees|dollars)\b/.test(text)){const next=/inr|rupees/.test(text)?"INR":"USD";if(next==="INR"&&!fx?.rates.INR)return reply("Fetch the latest INR rate in Settings before switching.");return safeMutation(s,"settings",{currency:next},`Display the whole dashboard in ${next}. Stored USD balances stay exact.`);}
 if(/\b(delete|remove|cancel)\b/.test(text)&&/\bgoal\b/.test(text)){if(!g)return needGoal();return open("close",`Choose why you’re deleting ${g.name}. If you already bought it, enter the actual cost to calculate any shortfall.`,g.id);}
 if(/\b(bought|purchased|buy it|mark.*win)\b/.test(text)){if(!g)return needGoal();return open("close",`Confirm whether you bought ${g.name} and enter the actual price. Full funding plus a confirmed purchase becomes a WIN; shortfalls go to LOSSES.`,g.id);}
 if(/\b(split|suggest.*allocat|allocate.*even|spread.*money)\b/.test(text)){try{const amount=findAmount(raw,currency,fx)?.cents??available(s);if(amount>available(s))return reply("That’s more than your available money. Record income first or choose a smaller split.");const allocations=suggestSplit(s,amount);if(!allocations.length)return reply("There’s no available money to split, or your goals are fully funded. Record earnings or confirm a goal budget first.");return safeMutation(s,"split",{allocations,date:today,note:"Gullie suggested split"},"Reserve money toward unfinished goals:\n"+allocations.map(a=>`${s.goals.find(g=>g.id===a.goalId)?.name}: ${fmt(a.amountCents)}`).join("\n"));}catch(e){return reply((e as Error).message);}}
 if(/\b(eta|when|how long|pace|per week|weekly|per month|monthly|daily|per day)\b/.test(text)&&g){try{const a=findAmount(raw,currency,fx),interval=/week/.test(text)?7:/month/.test(text)?30:1;if(a&&/per (day|week|month)|weekly|monthly|daily/.test(text)){const left=Math.max(0,g.targetCents-balance(s,g.id)),days=Math.ceil(left/a.cents*interval);return reply(`At ${fmt(a.cents)} every ${interval} ${interval===1?"day":"days"}, ${g.name} needs about ${days} more days to cover ${fmt(left)}. This is a scenario; no deposit or recurring schedule has been added.`);}const eta=goalEta(s,g,today);return reply(eta?`${g.name}: ${eta.days===0?"ready":`about ${eta.days} days, around ${eta.date??"a long-term date"}`}. Pace = total deposits ÷ elapsed days since the goal started (${eta.start}). Remaining amount ÷ daily pace gives ETA. It assumes you keep saving at that pace.`:"ETA appears after the first deposit. It uses the goal start date, total deposits, and elapsed days; future deposits aren’t guaranteed.");}catch(e){return reply((e as Error).message);}}
 if(/\b(earned|earning|income|deposit|received|record)\b/.test(text)&&!/\b(how|what|why|explain|show)\b/.test(text)&&!/\b(?:from|release|allocate|reserve|edit|change|delete|remove)\b/.test(text)&&(!g||/earned|earning/.test(text))){try{const a=findAmount(raw,currency,fx);if(!a)return reply("How much did you earn? Say ‘I earned $50’ or ‘Record income of 5,000 rupees’.");return safeMutation(s,"income",{amountCents:a.cents,conversion:a.conversion,date:today,note:"Recorded with Gullie"},`Record ${fmt(a.cents)} as earned income, available to allocate.`);}catch(e){return reply((e as Error).message);}}
 if(/\b(create|new|start|want|save for|saving for)\b/.test(text)&&(/goal|buy|save for|saving for/.test(text))){try{const a=findAmount(raw,currency,fx);if(!a)return reply("What is the goal name and budget? For example, ‘Create an iPhone 18 Pro Max goal for $1,400’.");let name=a.normalized.replace(a.match,"").replace(/^.*?\b(?:create|start|new|want to buy|save for|saving for)\s*(?:a |an |the )?/i,"").replace(/\b(?:goal|gullak|piggy bank|budget|target|with a|with|of|for|costing|at|dollars?|rupees?|usd|inr)\b/gi,"").replace(/[.,:;]+$/g,"").replace(/\s+/g," ").trim();if(!name||name.length>60)return reply("Give me a goal name up to 60 characters and its budget.");return safeMutation(s,"createGoal",{name,targetCents:a.cents,targetConversion:a.conversion,category:"auto",startedOn:today,date:"",note:""},`Create ${name} with a ${fmt(a.cents)} goal. Its category and icon will be chosen from its name.`);}catch(e){return reply((e as Error).message);}}
 if(/\b(edit|rename|change|update)\b/.test(text)&&g){try{const a=findAmount(raw,currency,fx),renamed=raw.match(/\brename\s+.+?\s+to\s+["“]?(.+?)["”]?$/i)?.[1]?.trim();if(!a&&!renamed)return open("goal",`Edit the name, budget, category, date, or note for ${g.name}.`,g.id);return safeMutation(s,"editGoal",{goalId:g.id,name:renamed??g.name,targetCents:a?.cents??g.targetCents,targetConversion:a?.conversion??g.targetConversion,category:g.categoryOverride?g.category:"auto",date:g.date,note:g.note},`Update ${g.name}${renamed?` to ${renamed}`:""}${a?` with a ${fmt(a.cents)} goal`:""}.`);}catch(e){return reply((e as Error).message);}}
 if(/\b(add|reserve|allocate|put|deposit|release|withdraw)\b/.test(text)&&g){try{const a=findAmount(raw,currency,fx);if(!a)return reply(`How much should I ${/release/.test(text)?"release from":"add to"} ${g.name}? Include USD or INR if it differs from your display currency.`);if(/release|withdraw/.test(text))return safeMutation(s,"release",{goalId:g.id,amountCents:a.cents,conversion:a.conversion,date:today,note:"Gullie release"},`Release ${fmt(a.cents)} from ${g.name} to available.`);if(!/from (?:income|available|pool|savings|new money|external)/.test(text)&&!/reserve|allocate/.test(text))return reply(`Should ${fmt(a.cents)} for ${g.name} come from recorded income or new money / existing savings? Say ‘Allocate ${a.input} ${a.currency} to ${g.name} from income’ or ‘Add ${a.input} ${a.currency} to ${g.name} from savings’.`);const source=/from (?:savings|new money|external)/.test(text)?"external":"pool";return safeMutation(s,"contribute",{goalId:g.id,amountCents:a.cents,conversion:a.conversion,source,date:today,note:"Gullie allocation"},`${source==="pool"?"Reserve recorded income":"Add new money / existing savings"}: ${fmt(a.cents)} for ${g.name}.`);}catch(e){return reply((e as Error).message);}}
 if(/\b(add|reserve|allocate|put|release|edit|rename|change|delete)\b/.test(text)&&matches.length>1)return needGoal();
 if(/\b(funded|available|balance|earned|earning|income|loss|losses|wins|category|categories|currency|rate|eta|history|progress|goal)\b/.test(text)){if(g)return reply(`${g.name} is in ${categoryLabel(g.category)}. Current: ${fmt(balance(s,g.id))}; Goal: ${fmt(g.targetCents)}; remaining: ${fmt(Math.max(0,g.targetCents-balance(s,g.id)))}. ${g.draft?"Confirm its budget before funding.":"It moves to WINS after full funding and a confirmed purchase."}`);if(/loss/.test(text))return reply(`LOSSES totals ${fmt(-losses(s))}. Each loss is actual purchase cost minus money funded for that item when you bought it. It doesn’t reduce another goal or invent income. Edit the purchase in History to correct a price.`);if(/currency|rate/.test(text))return reply(`Your display currency is ${currency}. USD is the accounting currency. Switching display does not change saved balances. ${fx?.rates.INR?`Latest published rate: 1 USD = ${fx.rates.INR.rate} INR (${fx.rates.INR.date}). `:""}Rates are daily reference rates, not live trading prices. Each non-USD deposit keeps its original currency and conversion.`);if(/categor/.test(text))return reply("Goals are grouped into Tech, Home, Mobility, Travel & experiences, and Lifestyle. The name determines the category and a specific icon. You can override the category in Edit goal → More details.");if(/eta/.test(text))return reply("ETA starts after your first deposit. Daily pace is total deposited ÷ elapsed days since the goal started. Remaining amount ÷ daily pace estimates days left. Resetting funding restarts it. Ask about a named goal to see its estimate.");return reply(dashboardSummary(s,fx,today,/explain|why/.test(text)));}
 return reply("I can help with this dashboard. Try ‘Summarize my goals’, ‘Explain my balances’, ‘Create a car goal for $8,000’, ‘I earned $50’, or ‘Read that aloud’. For a change, include the goal name, amount, and money source.",false);
}
