"use client";
import { useEffect, useRef, useState } from "react";
import { Mic, Square } from "lucide-react";
type SpeechEvent={resultIndex:number;results:{length:number;[index:number]:{isFinal:boolean;[index:number]:{transcript:string}}}};
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((e:SpeechEvent)=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
type SpeechWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
export function useVoice(onText:(text:string)=>void){const [supported,setSupported]=useState(false),[listening,setListening]=useState(false),[error,setError]=useState("");const speech=useRef<Recognition|null>(null),callback=useRef(onText);callback.current=onText;
 useEffect(()=>{const w=window as SpeechWindow;setSupported(!!(w.SpeechRecognition||w.webkitSpeechRecognition));return()=>{if(speech.current){speech.current.onend=null;speech.current.onresult=null;speech.current.onerror=null;speech.current.abort();speech.current=null;}};},[]);
 const stop=()=>{speech.current?.stop();setListening(false);};
 const toggle=()=>{if(listening){stop();return;}const w=window as SpeechWindow,Constructor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Constructor){setError("Voice entry isn’t available in this browser. Use the microphone on your keyboard to dictate into the text box.");return;}setError("");if(speech.current){speech.current.onend=null;speech.current.onresult=null;speech.current.onerror=null;speech.current.abort();}const recognition=new Constructor();speech.current=recognition;recognition.lang="en-US";recognition.continuous=false;recognition.interimResults=true;recognition.onresult=e=>{let transcript="";for(let i=0;i<e.results.length;i++)transcript+=e.results[i][0].transcript;callback.current(transcript.trim());};recognition.onerror=e=>{setListening(false);setError(e.error==="not-allowed"||e.error==="service-not-allowed"?"Microphone access was declined. Allow it in browser settings, or use keyboard dictation.":e.error==="no-speech"?"No speech heard. Try again.":e.error==="aborted"?"":"Voice recognition is unavailable. Try again or type your request.");};recognition.onend=()=>{setListening(false);if(speech.current===recognition)speech.current=null;};try{recognition.start();setListening(true);}catch{setListening(false);setError("Voice could not start. Try again or use keyboard dictation.");}};
 return {supported,listening,error,toggle,stop};}
export function VoiceButton({voice,disabled=false}:{voice:ReturnType<typeof useVoice>;disabled?:boolean}){return <button type="button" className={`button secondary voice-button ${voice.listening?"listening":""}`} onClick={voice.toggle} disabled={disabled} aria-pressed={voice.listening}>{voice.listening?<Square size={16}/>:<Mic size={17}/>} {voice.listening?"Stop listening":"Use voice"}</button>;}
export default function VoiceEntry({kind,onUse,currency,disabled=false}:{disabled?:boolean;kind:"goal"|"income";onUse:(text:string)=>void;currency:string}){const [text,setText]=useState(""),[shown,setShown]=useState(false);const voice=useVoice(t=>{setText(t);setShown(true);});useEffect(()=>{if(disabled)voice.stop();},[disabled]);return <div className="voice-entry"><VoiceButton voice={voice} disabled={disabled}/>{!voice.supported&&<p className="help-text">You can also use your keyboard’s microphone.</p>}{(shown||voice.error||voice.listening)&&<><p className="help-text">{voice.error||`Say ${kind==="goal"?`“Create a monitor goal for 400 ${currency}”`:`“I earned fifty dollars”`}. Your browser’s speech service transcribes your voice. Review before saving.`}</p><label className="form-label">Recognized text<textarea value={text} onChange={e=>setText(e.target.value)} rows={2} maxLength={1500}/></label><button type="button" className="text-button" disabled={!text.trim()||voice.listening} onClick={()=>{voice.stop();onUse(text);}}>Use this text</button></>}</div>;}
