"use client";
import {useEffect,useState} from "react";
import {ArrowRight,LogIn,UserPlus,Smartphone} from "lucide-react";
import Dashboard from "./dashboard";
import {trackUsage} from "@/lib/track-usage";
export default function Welcome({signInPath}:{signInPath:string}){const [guest,setGuest]=useState(false);useEffect(()=>{try{setGuest(localStorage.getItem("gullak-entry-mode")==="guest");}catch{}},[]);
 const prepareSignIn=()=>{trackUsage("sign_in_started");try{localStorage.removeItem("gullak-entry-mode");}catch{}};
 const enterGuest=()=>{trackUsage("guest_started");try{localStorage.setItem("gullak-entry-mode","guest");}catch{}setGuest(true);};
 const leaveGuest=()=>{try{localStorage.removeItem("gullak-entry-mode");}catch{}setGuest(false);};
 if(guest)return <Dashboard accountName="Guest" signOutPath="/" storageMode="guest" onLeaveGuest={leaveGuest}/>;
 return <main className="welcome-page"><a href="/" className="welcome-brand" aria-label="Gullak home"><picture><source srcSet="/favicon-dark.svg" media="(prefers-color-scheme: dark)"/><img src="/favicon-light.svg" width="60" height="60" alt="Gullak G dollar monogram"/></picture><span>gullak</span></a><div className="welcome-copy"><h1>A little closer.<br/>To the things you want.</h1><p>Set a goal. Put money aside. Make it happen.</p></div><div className="welcome-options"><a className="welcome-option" href={signInPath} target="_top" onClick={prepareSignIn}><LogIn size={21}/><div><strong>Log In</strong><span>Continue with your ChatGPT account.</span></div><ArrowRight size={18}/></a><a className="welcome-option" href={signInPath} target="_top" onClick={prepareSignIn}><UserPlus size={21}/><div><strong>Create an Account</strong><span>Use ChatGPT to save and sync across devices.</span></div><ArrowRight size={18}/></a><button className="welcome-option" onClick={enterGuest}><Smartphone size={21}/><div><strong>Continue as a Guest</strong><span>Your goals stay on this device.</span></div><ArrowRight size={18}/></button></div><p className="welcome-footnote">Signing in and creating an account both use ChatGPT. Your Gullak account is created automatically the first time you sign in. Guest data does not sync; clearing browser data removes it.</p><section className="welcome-about" aria-label="About Gullak"><h2>A simple savings goal tracker</h2><p>Plan for a new gadget, a trip, a home project, or whatever comes next. Create goals, record earnings, and choose how much to reserve for each one. See what is funded, what is available, and the progress you have made.</p><h3>Meet Gullie</h3><p>Ask Gullie to explain your balances, summarise your goals, or prepare a change in plain language. Review every proposed change before saving it. Gullak records your plan; it does not move bank money.</p><h3>Use it your way</h3><p>Try guest mode on this device, or sign in with ChatGPT to sync your dashboard. Use Gullak on a laptop or phone, and add it to your Safari Home Screen for quick access. Switch between USD and INR, keep your history, and download a backup.</p><a href="/privacy" className="text-link">Privacy and usage analytics</a></section></main>;
}
